disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - sorted_first_last
  - contains_over_first_not_nil
  - last_where

line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true

identifier_name:
  excluded:
    - id
    - to

excluded:
  - Echo.xcodeproj
  - .build
  - DerivedData
